/*
 * Code generated by Backengine
 *
 * https://backengine.dev
 */

import axios, { RawAxiosRequestHeaders } from "axios";
import { useState } from "react";

export interface ApiLeadRequest {
  ContactName: string;
  Email: string;
  PhoneNumber: string;
  InventoryID: string;
  LeadSource: string;
  InterestLevel: number;
  PreviousVisits?: boolean;
  [k: string]: unknown;
}

export interface ApiLeadResponse {
  id?: number;
  [k: string]: unknown;
}

function useLeadsPostMutation() {
  const [isError, setIsError] = useState(false);
  const [isLoading, setIsLoading] = useState(false);

  const headers = (): RawAxiosRequestHeaders => {
    const token = localStorage.getItem("engine-token");
    const defaultHeaders = {
      "Content-Type": "application/json",
    };
    return token
      ? {
          ...defaultHeaders,
          Authorization: `Bearer ${token}`,
        }
      : defaultHeaders;
  };

  const execute = async (body: ApiLeadRequest): Promise<ApiLeadResponse> => {
    setIsLoading(true);
    setIsError(false);

    const url = new URL(`https://backengine-d4x1.fly.dev/api/leads`);

    try {
      const response = await axios.post<ApiLeadResponse>(url.toString(), body, {
        headers: headers(),
      });
      return response.data;
    } catch (error) {
      setIsError(true);
      throw error;
    } finally {
      setIsLoading(false);
    }
  };

  return {
    execute,
    isError,
    isLoading,
  };
}

export default useLeadsPostMutation;
