/*
 * Code generated by Backengine
 *
 * https://backengine.dev
 */

import axios, { RawAxiosRequestHeaders } from "axios";
import { useState } from "react";

export interface ApiLeadsIdRequest {
  ContactName: string;
  Email: string;
  PhoneNumber: string;
  InventoryID: string;
  LeadSource: string;
  InterestLevel: number;
  PreviousVisits?: boolean;
  [k: string]: unknown;
}

export interface ApiLeadsIdResponse {
  id?: number;
  ContactName?: string;
  Email?: string;
  PhoneNumber?: string;
  InventoryID?: string;
  LeadSource?: string;
  InterestLevel?: number;
  PreviousVisits?: boolean;
  [k: string]: unknown;
}

function useLeadsIdPutMutation(id: number) {
  const [isError, setIsError] = useState(false);
  const [isLoading, setIsLoading] = useState(false);

  const headers = (): RawAxiosRequestHeaders => {
    const token = localStorage.getItem("engine-token");
    const defaultHeaders = {
      "Content-Type": "application/json",
    };
    return token
      ? {
          ...defaultHeaders,
          Authorization: `Bearer ${token}`,
        }
      : defaultHeaders;
  };

  const execute = async (
    body: ApiLeadsIdRequest,
  ): Promise<ApiLeadsIdResponse> => {
    setIsLoading(true);
    setIsError(false);

    const url = new URL(`https://backengine-d4x1.fly.dev/api/leads/${id}`);

    try {
      const response = await axios.put<ApiLeadsIdResponse>(
        url.toString(),
        body,
        {
          headers: headers(),
        },
      );
      return response.data;
    } catch (error) {
      setIsError(true);
      throw error;
    } finally {
      setIsLoading(false);
    }
  };

  return {
    execute,
    isError,
    isLoading,
  };
}

export default useLeadsIdPutMutation;
