/*
 * Code generated by Backengine
 *
 * https://backengine.dev
 */

import axios from "axios";
import { useState } from "react";

type SignUpRequest = {
  email: string;
  password: string;
};

function useSignUpMutation() {
  const [isError, setIsError] = useState(false);
  const [isLoading, setIsLoading] = useState(false);

  const signUp = async ({ email, password }: SignUpRequest): Promise<void> => {
    setIsLoading(true);
    setIsError(false);

    try {
      await axios.post(
        `https://backengine-d4x1.fly.dev/api/signup`,
        {
          email,
          password,
        },
        {
          headers: { "Content-Type": "application/json" },
        },
      );
    } catch (error) {
      setIsError(true);
      throw error;
    } finally {
      setIsLoading(false);
    }
  };

  return {
    signUp,
    isLoading,
    isError,
  };
}

export default useSignUpMutation;
