/*
 * Code generated by Backengine
 *
 * https://backengine.dev
 */

function useSignOutMutation() {
  const signOut = async () => {
    localStorage.removeItem("engine-token");
    window.location.reload();
  };

  return {
    signOut,
  };
}

export default useSignOutMutation;
